### ISSUE TITLE
db baru no sensor

### ISSUE THREAD

**Issue by beryindo** [ngadmini/Grabbing-Blacklist-for-Bind9-RPZ#126]
db baru no sensor disini om
https://trustpositif.kominfo.go.id/assets/db/domains_isp

**Comment by ngadmini** [comment]
terima kasih infonya
[grab_urls](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/eccfd883c5540619cbf257ea51ebe201d2b289d6/libs/grab_urls#L8) dan [grab_http.sh](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/master/libs/grab_http.sh) segera di sesuaikan

**Comment by ngadmini** [comment]
[grab_urls](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/5efb2b391501eadc9ae80cd832b821bd15b27660/libs/grab_urls#L8) fixed

**Comment by ngadmini** [comment]
terimakasih infonya bos 

[grab_urls](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/5efb2b391501eadc9ae80cd832b821bd15b27660/libs/grab_urls#L8) fixed
