### ISSUE TITLE
add url list

### ISSUE THREAD

**Issue by alsyundawy** [ngadmini/Grabbing-Blacklist-for-Bind9-RPZ#131]
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts
https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts

https://github.com/blocklistproject/Lists/blob/master/tracking.txt
https://github.com/blocklistproject/Lists/blob/master/tracking.ip
https://github.com/blocklistproject/Lists/blob/master/scam.txt
https://github.com/blocklistproject/Lists/blob/master/redirect.txt
https://github.com/blocklistproject/Lists/blob/master/ransomware.txt
https://github.com/blocklistproject/Lists/blob/master/porn.txt
https://github.com/blocklistproject/Lists/blob/master/piracy.txt
https://github.com/blocklistproject/Lists/blob/master/phishing.txt
https://github.com/blocklistproject/Lists/blob/master/malware.txt
https://github.com/blocklistproject/Lists/blob/master/malware.ip
https://github.com/blocklistproject/Lists/blob/master/gambling.txt
https://github.com/blocklistproject/Lists/blob/master/fraud.txt
https://github.com/blocklistproject/Lists/blob/master/drugs.txt
https://github.com/blocklistproject/Lists/blob/master/ads.txt
https://github.com/blocklistproject/Lists/blob/master/abuse.txt
https://github.com/blocklistproject/Lists/blob/master/abuse.ip

**Comment by ngadmini** [comment]
Banyak yang harus diubah bro kalau mau menambah item di grab_urls.
Tapi intinya begini, misalnya ingin menambah url :
```
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts
```
maka harus membuat regex sehingga hanya diperoleh domains
```
ck.getcookiestxt.com
eu1.clevertap-prod.com
wizhumpgyros.com
coccyxwickimp.com
webmail-who-int.000webhostapp.com
010sec.com
```
selanjutnya diperlukan penyesuaian pada file [grab_config](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/18a1737b2f73d769647258ca4bb693b90b2a5fff/libs/grab_config#L46), [grab_library](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/18a1737b2f73d769647258ca4bb693b90b2a5fff/libs/grab_library#L329) dan [grab_http.sh](https://github.com/ngadmini/Grabbing-Blacklist-for-Bind9-RPZ/blob/master/libs/grab_http.sh) mulai baris 135 (sesuai kategori)

regards
ngadmini
