### ISSUE TITLE
regex

### ISSUE THREAD

**Issue by alsyundawy** [ngadmini/Grabbing-Blacklist-for-Bind9-RPZ#134]
slot,maxwin,gacor,dewa

**Comment by ngadmini** [comment]
Makacih
Segera diperiksa

**Comment by alsyundawy** [comment]
biasanya ada embel2 di bagian depan atau belakang domain dengan angka 7,8 atau 9. misal maxwin88 atau 88slot.

oh iya karena mereka para bandar punya anggaran min perbulan sebanyak $1000 untuk pembelian domain, tidak mustahil mereka order dan menggunakan domain tld dan cctld seperti yg terdaftar di list domain iana (https://data.iana.org/TLD/tlds-alpha-by-domain.txt) 

mohon dibantu untuk regexnya

**Comment by ngadmini** [comment]
> biasanya ada embel2 di bagian depan atau belakang domain dengan angka 7,8 atau 9. misal maxwin88 atau 88slot.
> 
> oh iya karena mereka para bandar punya anggaran min perbulan sebanyak $1000 untuk pembelian domain, tidak mustahil mereka order dan menggunakan domain tld dan cctld seperti yg terdaftar di list domain iana (https://data.iana.org/TLD/tlds-alpha-by-domain.txt)
> 
> mohon dibantu untuk regexnya

Tolong link domain list yang anda pakai
